import { serve } from 'https://deno.land/std@0.182.0/http/server.ts'
import { createClient } from 'https://esm.sh/v135/@supabase/supabase-js@2.39.0/dist/module/index.js'
import { appendEvent } from '../_shared/canonicalEventHelper.ts'
import { buildCanonicalFieldSchemaV1, hashCanonicalFieldSchemaV1 } from '../_shared/fieldSchema.ts'
import { withRateLimit } from '../_shared/ratelimit.ts'
import {
  generateSecretToken,
  createTokenHash,
  encryptToken,
} from '../_shared/cryptoHelper.ts'
import { getCorsHeaders } from '../_shared/cors.ts'

interface Signer {
  email: string
  name?: string
  signingOrder: number
  requireLogin?: boolean
  requireNda?: boolean
  quickAccess?: boolean
  // ZK Mode - generated by owner client
  wrappedKey?: string
  wrapIv?: string
  recipientSalt?: string
}

interface WorkflowFieldInput {
  external_field_id?: string
  document_entity_id?: string
  field_type?: 'signature' | 'text' | 'date' | string
  label?: string | null
  placeholder?: string | null
  position?: Record<string, unknown>
  assigned_to?: string | null
  assigned_signer_id?: string | null
  required?: boolean
  value?: string | null
  metadata?: Record<string, unknown> | null
  batch_id?: string | null
  apply_to_all_pages?: boolean | null
}

interface StartWorkflowRequest {
  documentUrl: string
  documentHash: string
  originalFilename: string
  documentEntityId?: string
  signatureType?: 'ECOSIGN' | 'SIGNNOW'
  ndaText?: string | null
  ndaEnabled?: boolean
  requireSequential?: boolean
  canvasSnapshot?: Record<string, unknown> | null
  workflowFields?: WorkflowFieldInput[] | null
  signers: Signer[]
  forensicConfig: {
    rfc3161: boolean
    polygon: boolean
    bitcoin: boolean
  }
  /**
   * Delivery mode for signer notifications.
   * - 'email': Send invitation emails to signers automatically (default)
   * - 'link': No automatic emails, creator shares link manually
   * Immutable after workflow creation.
   */
  deliveryMode?: 'email' | 'link'
  /**
   * Controls whether participants can access the final PDF/ECO after signing is complete.
   * - 'owner_only' (default): only the owner can download the final artifact
   * - 'participants': all signers who signed can also access the final artifact
   */
  finalDocumentVisibility?: 'owner_only' | 'participants'
}

function extractStoragePath(url: string): string | null {
  try {
    const parsed = new URL(url)
    const match = parsed.pathname.match(/\/storage\/v1\/object\/(?:sign|public)\/([^/]+)\/(.+)$/)
    if (!match) return null
    const path = decodeURIComponent(match[2])
    return path || null
  } catch {
    return null
  }
}

const FIELD_TYPES = new Set(['signature', 'text', 'date'])

function normalizeWorkflowFields(
  fields: WorkflowFieldInput[],
  documentEntityId: string,
  userId: string
): { fields: Record<string, unknown>[]; batchIds: string[]; error?: string } {
  const normalized: Record<string, unknown>[] = []
  const batchIds = new Set<string>()

  for (const field of fields) {
    const fieldType = typeof field.field_type === 'string' ? field.field_type : ''
    if (!FIELD_TYPES.has(fieldType)) {
      return { fields: [], batchIds: [], error: `invalid_field_type:${fieldType || 'missing'}` }
    }

    const position = field.position
    if (!position || typeof position !== 'object') {
      return { fields: [], batchIds: [], error: 'invalid_position' }
    }
    const pos = position as Record<string, unknown>
    const coords = ['page', 'x', 'y', 'width', 'height']
    for (const key of coords) {
      const value = pos[key]
      if (typeof value !== 'number' || Number.isNaN(value)) {
        return { fields: [], batchIds: [], error: `invalid_position_${key}` }
      }
    }

    const batchId = typeof field.batch_id === 'string' && field.batch_id.trim().length > 0
      ? field.batch_id.trim()
      : crypto.randomUUID()
    const externalFieldId = typeof field.external_field_id === 'string' && field.external_field_id.trim().length > 0
      ? field.external_field_id.trim()
      : (typeof (field.metadata as any)?.frontend_id === 'string'
          ? String((field.metadata as any).frontend_id)
          : crypto.randomUUID())

    batchIds.add(batchId)

    normalized.push({
      external_field_id: externalFieldId,
      document_entity_id: documentEntityId,
      field_type: fieldType,
      label: field.label ?? null,
      placeholder: field.placeholder ?? null,
      position: position,
      assigned_to: typeof field.assigned_to === 'string' ? field.assigned_to.trim() : null,
      assigned_signer_id: field.assigned_signer_id ?? null,
      required: Boolean(field.required),
      value: field.value ?? null,
      metadata: field.metadata ?? null,
      batch_id: batchId,
      apply_to_all_pages: Boolean(field.apply_to_all_pages),
      created_by: userId,
    })
  }

  return { fields: normalized, batchIds: Array.from(batchIds) }
}

async function triggerEmailDelivery(supabase: ReturnType<typeof createClient>) {
  try {
    const cronSecret = Deno.env.get('CRON_SECRET')
    if (!cronSecret) {
      console.warn('send-pending-emails skipped: missing CRON_SECRET')
      return
    }
    await supabase.functions.invoke('send-pending-emails', {
      headers: { 'x-cron-secret': cronSecret }
    })
  } catch (error) {
    console.warn('send-pending-emails invoke failed', error)
  }
}

serve(withRateLimit('workflow', async (req) => {
  const { isAllowed, headers: corsHeaders } = getCorsHeaders(req.headers.get('origin') ?? undefined)

  const jsonResponse = (data: unknown, status = 200) =>
    new Response(JSON.stringify(data), {
      status,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' }
    })

  if (req.method === 'OPTIONS') {
    if (!isAllowed) {
      return new Response('Forbidden', { status: 403, headers: corsHeaders })
    }
    return new Response('ok', { headers: corsHeaders })
  }

  if (!isAllowed) {
    return jsonResponse({ error: 'Origin not allowed' }, 403)
  }

  if (req.method !== 'POST') {
    return jsonResponse({ error: 'Method not allowed' }, 405)
  }

  try {
    const supabaseUrl = Deno.env.get('SUPABASE_URL')!
    const supabaseServiceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!
    const supabase = createClient(supabaseUrl, supabaseServiceKey) as any

    const authHeader = req.headers.get('Authorization')
    if (!authHeader) {
      return jsonResponse({ error: 'Missing authorization' }, 401)
    }

    const supabaseAuth = createClient(
      supabaseUrl,
      Deno.env.get('SUPABASE_ANON_KEY')!,
      { global: { headers: { Authorization: authHeader } } }
    )

    const { data: { user }, error: userError } = await supabaseAuth.auth.getUser()
    if (userError || !user) {
      return jsonResponse({ error: 'Unauthorized', details: userError?.message }, 401)
    }

    const body: StartWorkflowRequest = await req.json()
    const {
      documentUrl,
      documentHash,
      originalFilename,
      documentEntityId,
      signatureType,
      ndaText,
      ndaEnabled,
      signers,
      forensicConfig,
      deliveryMode = 'email', // Default to email for backwards compatibility
      finalDocumentVisibility = 'owner_only',
      requireSequential = true,
    } = body

    if (!documentUrl || !documentHash || !originalFilename || !signers || signers.length === 0) {
      return jsonResponse({ error: 'Missing required fields' }, 400)
    }

    if (typeof requireSequential !== 'boolean') {
      return jsonResponse({ error: 'Invalid requireSequential. Must be boolean' }, 400)
    }

    // Validate deliveryMode if provided
    if (deliveryMode && !['email', 'link'].includes(deliveryMode)) {
      return jsonResponse({ error: 'Invalid deliveryMode. Must be "email" or "link"' }, 400)
    }

    // Validate finalDocumentVisibility
    if (!['owner_only', 'participants'].includes(finalDocumentVisibility)) {
      return jsonResponse({ error: 'Invalid finalDocumentVisibility. Must be "owner_only" or "participants"' }, 400)
    }

    const requiresNda = ndaEnabled === true
      ? true
      : ndaEnabled === false
      ? false
      : signers.some((s) => s.requireNda === true);
    const trimmedNda = typeof ndaText === 'string' ? ndaText.trim() : '';
    if (requiresNda && !trimmedNda) {
      return jsonResponse(
        { error: 'NDA required but missing ndaText' },
        400
      )
    }

    if (trimmedNda.length > 10000) {
      return jsonResponse(
        { error: 'NDA text too long (max 10000 chars)' },
        400
      )
    }

    const documentPath = extractStoragePath(documentUrl)

    const canvasSnapshot =
      body.canvasSnapshot && typeof body.canvasSnapshot === 'object'
        ? body.canvasSnapshot
        : null
    const workflowFields = Array.isArray(body.workflowFields) ? body.workflowFields : null

    const workflowPayload = {
      owner_id: user.id,
      original_filename: originalFilename,
      original_file_url: documentUrl,
      document_path: documentPath ?? null,
      document_hash: documentHash,
      status: 'active',
      require_sequential: requireSequential,
      forensic_config: forensicConfig,
      nda_text: trimmedNda || null,
      delivery_mode: deliveryMode, // 'email' or 'link' - immutable after creation
      final_document_visibility: finalDocumentVisibility,
      ...(canvasSnapshot ? { canvas_snapshot: canvasSnapshot } : {}),
      ...(signatureType ? { signature_type: signatureType } : {}),
      ...(documentEntityId ? { document_entity_id: documentEntityId } : {})
    }

    const { data: workflow, error: workflowError } = await supabase
      .from('signature_workflows')
      .insert(workflowPayload)
      .select()
      .single()

    if (workflowError || !workflow) {
      return jsonResponse({ error: 'Failed to create workflow', details: workflowError?.message }, 500)
    }

    const { data: version, error: versionError } = await supabase
      .from('workflow_versions')
      .insert({
        workflow_id: workflow.id,
        version_number: 1,
        document_url: documentUrl,
        document_hash: documentHash,
        change_reason: 'initial',
        status: 'active'
      })
      .select()
      .single()

    if (versionError || !version) {
      return jsonResponse({ error: 'Failed to create workflow version', details: versionError?.message }, 500)
    }

    const cleanupWorkflow = async () => {
      try { await supabase.from('workflow_signers').delete().eq('workflow_id', workflow.id) } catch {}
      try { await supabase.from('workflow_versions').delete().eq('workflow_id', workflow.id) } catch {}
      try { await supabase.from('signature_workflows').delete().eq('id', workflow.id) } catch {}
    }

    if (workflowFields && workflowFields.length > 0) {
      if (!workflow.document_entity_id) {
        await cleanupWorkflow()
        return jsonResponse({
          error: 'missing_document_entity_id',
          message: 'No se pudo persistir campos sin document_entity_id.'
        }, 409)
      }

      const normalizedFields = normalizeWorkflowFields(
        workflowFields,
        workflow.document_entity_id,
        user.id
      )

      if (normalizedFields.error) {
        await cleanupWorkflow()
        return jsonResponse({
          error: 'invalid_workflow_fields',
          details: normalizedFields.error
        }, 400)
      }

      const batchesPayload = normalizedFields.batchIds.map((batchId) => ({
        id: batchId,
        document_entity_id: workflow.document_entity_id,
        origin: 'user_created'
      }))

      const { error: batchUpsertError } = await supabase
        .from('batches')
        .upsert(batchesPayload, { onConflict: 'id' })

      if (batchUpsertError) {
        await cleanupWorkflow()
        return jsonResponse({ error: 'failed_to_create_batches', details: batchUpsertError.message }, 500)
      }

      const { error: fieldsInsertError } = await supabase
        .from('workflow_fields')
        .upsert(normalizedFields.fields, { onConflict: 'external_field_id' })

      if (fieldsInsertError) {
        await cleanupWorkflow()
        return jsonResponse({ error: 'failed_to_create_workflow_fields', details: fieldsInsertError.message }, 500)
      }
    }

    const signersToInsert = []
    const accessTokens: Record<string, { token: string, tokenHash: string }> = {}
    const tokenLifetimeDays = 7

    for (const signer of signers) {
      const token = await generateSecretToken()
      const tokenHash = await createTokenHash(token)
      const { ciphertext, nonce } = await encryptToken(token)
      const expiresAt = new Date()
      expiresAt.setDate(expiresAt.getDate() + tokenLifetimeDays)

      const quickAccess = signer.quickAccess ?? false
      const requireLogin = quickAccess ? false : (signer.requireLogin ?? true)
      const requireNda = quickAccess ? false : (signer.requireNda === true)

      // ZK Mode: If owner provides wrapped key material, use it
      const hasZkMaterial = signer.wrappedKey && signer.wrapIv && signer.recipientSalt
      
      const signerRecord: Record<string, unknown> = {
        workflow_id: workflow.id,
        signing_order: signer.signingOrder,
        email: signer.email,
        name: signer.name || null,
        require_login: requireLogin,
        require_nda: requireNda,
        quick_access: quickAccess,
        // Status will be promoted to ready_to_sign only after batch binding succeeds.
        status: requireSequential ? 'invited' : 'ready_to_sign',
        access_token_hash: tokenHash,
        access_token_ciphertext: ciphertext,
        access_token_nonce: nonce,
        token_expires_at: expiresAt.toISOString()
      }

      // ZK Mode fields - if provided by owner client
      if (hasZkMaterial) {
        signerRecord.wrapped_key = signer.wrappedKey
        signerRecord.wrap_iv = signer.wrapIv
        signerRecord.recipient_salt = signer.recipientSalt
        signerRecord.key_mode = 'wrapped'
        console.log('[ZK] Stored wrapped key for signer:', signer.email)
      } else {
        signerRecord.key_mode = 'legacy'
      }

      signersToInsert.push(signerRecord)
      accessTokens[signer.email] = { token, tokenHash }
    }

    // HYPOTHESIS DEBUGGING: Log the exact payload before the insert.
    console.log('[DEBUG] signersToInsert payload:', JSON.stringify(signersToInsert, null, 2));

    const { data: insertedSigners, error: signersError } = await supabase
      .from('workflow_signers')
      .insert(signersToInsert)
      .select('id, email, status, signing_order')

    if (signersError) {
      // HYPOTHESIS DEBUGGING: Log insert failure.
      console.error('[DEBUG] Failed to insert signers.', signersError);
      return jsonResponse({ error: 'Failed to create signers', details: signersError?.message }, 500)
    }

    // HYPOTHESIS DEBUGGING: Log insert success.
    console.log(`[DEBUG] Successfully inserted ${insertedSigners?.length || 0} signers.`);
    
    // ... (Canonical event logging remains the same)

    const appUrl = Deno.env.get('APP_URL') || 'https://app.ecosign.app'

    // P1.3 — Bind workflow_fields (batch_id + assigned_to email) to batches.assigned_signer_id
    // and enforce: each signer must have >= 1 assigned batch before we allow signing.
    if (!workflow.document_entity_id) {
      await cleanupWorkflow()
      return jsonResponse({
        error: 'missing_document_entity_id',
        message: 'No se pudo iniciar el workflow sin document_entity_id.'
      }, 409)
    }

    const { data: wfFields, error: wfFieldsErr } = await supabase
      .from('workflow_fields')
      .select('batch_id, assigned_to')
      .eq('document_entity_id', workflow.document_entity_id)

    if (wfFieldsErr) {
      console.error('Failed to fetch workflow_fields for binding', wfFieldsErr)
      await cleanupWorkflow()
      return jsonResponse({ error: 'failed_to_bind_fields', details: wfFieldsErr.message }, 500)
    }

    const batchToEmail = new Map<string, string>()
    const unassignedBatchIds = new Set<string>()

    for (const row of (wfFields || []) as any[]) {
      const bid = row.batch_id as string | null
      if (!bid) continue
      const email = (row.assigned_to as string | null)?.trim().toLowerCase() || null
      if (!email) {
        unassignedBatchIds.add(bid)
        continue
      }
      const existing = batchToEmail.get(bid)
      if (existing && existing !== email) {
        await cleanupWorkflow()
        return jsonResponse({
          error: 'inconsistent_batch_assignment',
          message: `Batch ${bid} tiene assigned_to inconsistente.`
        }, 409)
      }
      batchToEmail.set(bid, email)
    }

    if (unassignedBatchIds.size > 0) {
      await cleanupWorkflow()
      return jsonResponse({
        error: 'missing_signature_batch',
        message: 'Hay batches sin asignar a un firmante.',
        unassigned_batch_ids: Array.from(unassignedBatchIds)
      }, 409)
    }

    const signerByEmail = new Map<string, any>()
    for (const s of insertedSigners || []) {
      const email = (s.email as string).trim().toLowerCase()
      signerByEmail.set(email, s)
    }

    const batchUpdates: { id: string; document_entity_id: string; assigned_signer_id: string }[] = []
    const unknownEmails = new Set<string>()
    for (const [bid, email] of batchToEmail.entries()) {
      const signer = signerByEmail.get(email)
      if (!signer) {
        unknownEmails.add(email)
        continue
      }
      // Upsert must include document_entity_id in case the batches row does not exist yet.
      batchUpdates.push({
        id: bid,
        document_entity_id: workflow.document_entity_id,
        assigned_signer_id: signer.id
      })
    }

    if (unknownEmails.size > 0) {
      await cleanupWorkflow()
      return jsonResponse({
        error: 'missing_signature_batch',
        message: 'Hay batches asignados a emails que no existen en la lista de firmantes.',
        unknown_emails: Array.from(unknownEmails)
      }, 409)
    }

    if (batchUpdates.length === 0) {
      await cleanupWorkflow()
      return jsonResponse({
        error: 'missing_signature_batch',
        message: 'No hay batches asignados a firmantes.'
      }, 409)
    }

    const { error: batchUpdErr } = await supabase
      .from('batches')
      .upsert(batchUpdates, { onConflict: 'id' })

    if (batchUpdErr) {
      console.error('Failed to update batch assignments', batchUpdErr)
      await cleanupWorkflow()
      return jsonResponse({ error: 'failed_to_bind_fields', details: batchUpdErr.message }, 500)
    }

    // Canonical assignment: persist signer UUID on workflow_fields for hashing.
    const fieldAssignmentResults = await Promise.all(
      batchUpdates.map((b) =>
        supabase
          .from('workflow_fields')
          .update({ assigned_signer_id: b.assigned_signer_id })
          .eq('document_entity_id', b.document_entity_id)
          .eq('batch_id', b.id)
      )
    )

    const fieldAssignmentError = fieldAssignmentResults.find((r) => r.error)?.error
    if (fieldAssignmentError) {
      console.error('Failed to update workflow_fields assigned_signer_id', fieldAssignmentError)
      await cleanupWorkflow()
      return jsonResponse({ error: 'failed_to_bind_fields', details: fieldAssignmentError.message }, 500)
    }

    // Canonical: compute fields_schema_hash after assignment is resolved.
    try {
      const { data: schemaFields, error: schemaErr } = await supabase
        .from('workflow_fields')
        .select('external_field_id, field_type, position, required, assigned_signer_id, metadata')
        .eq('document_entity_id', workflow.document_entity_id)

      if (schemaErr) {
        console.warn('fields_schema_hash: failed to load workflow_fields', schemaErr)
      } else {
        const schema = buildCanonicalFieldSchemaV1({
          workflow_id: workflow.id,
          document_entity_id: workflow.document_entity_id,
          fields: (schemaFields || []) as any
        })
        const schemaHash = await hashCanonicalFieldSchemaV1(schema)
        const committedAt = new Date().toISOString()

        await supabase
          .from('signature_workflows')
          .update({
            fields_schema_hash: schemaHash,
            fields_schema_version: 1,
            fields_schema_committed_at: committedAt
          })
          .eq('id', workflow.id)

        await appendEvent(
          supabase as any,
          {
            event_type: 'fields.schema.committed',
            workflow_id: workflow.id,
            signer_id: null,
            payload: {
              document_entity_id: workflow.document_entity_id,
              fields_schema_hash: schemaHash,
              schema_version: 1,
              fields_count: schema.fields.length
            }
          },
          'start-signature-workflow'
        )
      }
    } catch (schemaHashErr) {
      console.warn('fields_schema_hash: compute failed (best-effort)', schemaHashErr)
    }

    // Enforce: each signer must have >= 1 batch.
    const signerIdsWithBatch = new Set(batchUpdates.map((b) => b.assigned_signer_id))
    const missingSigners = (insertedSigners || []).filter((s: any) => !signerIdsWithBatch.has(s.id))
    if (missingSigners.length > 0) {
      await cleanupWorkflow()
      return jsonResponse({
        error: 'missing_signature_batch',
        message: 'Faltan batches asignados para algunos firmantes.',
        missing_signers: missingSigners.map((s: any) => ({ id: s.id, email: s.email }))
      }, 409)
    }

    // Promote first signer to ready_to_sign only after binding succeeds (sequential flow).
    if (requireSequential) {
      const first = (insertedSigners || []).find((s: any) => s.signing_order === 1)
      if (first) {
        const { error: promoteErr } = await supabase
          .from('workflow_signers')
          .update({ status: 'ready_to_sign' })
          .eq('id', first.id)
        if (promoteErr) {
          console.error('Failed to promote first signer to ready_to_sign', promoteErr)
          await cleanupWorkflow()
          return jsonResponse({ error: 'failed_to_start', details: promoteErr.message }, 500)
        }
      }
    }

    // Create notification only for the first signer (sequential flow) or all signers (parallel)
    const notifications = []
    if (deliveryMode === 'email') {
      for (const insertedSigner of insertedSigners) {
        if (requireSequential && insertedSigner.signing_order !== 1) continue

        const token = accessTokens[insertedSigner.email]?.token
        if (!token) continue

        const signLink = `${appUrl}/sign/${token}`
        const expiresDate = new Date()
        expiresDate.setDate(expiresDate.getDate() + tokenLifetimeDays)
        const displayName = insertedSigner.email.split('@')[0]

        notifications.push({
          workflow_id: workflow.id,
          recipient_email: insertedSigner.email,
          recipient_type: 'signer',
          signer_id: insertedSigner.id,
          notification_type: 'your_turn_to_sign',
          subject: `Tenés un documento para firmar — ${originalFilename}`,
          body_html: `<html><body style="font-family: Arial, sans-serif; background-color: #f8fafc; padding: 24px; color: #0f172a;">
            <div style="max-width: 600px; margin: 0 auto; background: #ffffff; border-radius: 12px; padding: 24px; box-shadow: 0 10px 30px rgba(15, 23, 42, 0.08);">
              <p style="margin:0 0 12px;color:#0f172a;">Hola ${displayName},</p>
              <p style="margin:0 0 12px;color:#334155;">Te enviaron un documento para firmar:</p>
              <p style="margin:0 0 16px;font-weight:600;color:#0f172a;">${originalFilename}</p>
              <p style="margin:0 0 16px;color:#334155;">EcoSign certifica tu firma con trazabilidad completa y te entrega una copia segura, para que siempre tengas tu propia evidencia.</p>
              <p style="margin:16px 0;">
                <a href="${signLink}" style="display:inline-block;padding:14px 22px;background:#0ea5e9;color:#ffffff;text-decoration:none;border-radius:10px;font-weight:600;">Ver Documento</a>
              </p>
              <p style="margin:8px 0 0;color:#64748b;font-size:12px;">Al ingresar podés elegir firmar o rechazar el documento.</p>
              <p style="margin:0 0 12px;color:#64748b;font-size:12px;">Link válido hasta: ${expiresDate.toLocaleDateString('es-AR')}</p>
              <p style="margin:16px 0 0;color:#0f172a;font-weight:600;">EcoSign. Transparencia que acompaña.</p>
              <p style="margin:8px 0 0;color:#94a3b8;font-size:12px;">Este enlace es personal e intransferible. Todas las acciones quedan registradas por seguridad.</p>
            </div>
          </body></html>`,
          delivery_status: 'pending'
        })
      }
    }

    if (notifications.length > 0) {
      const { error: notifError } = await supabase
        .from('workflow_notifications')
        .insert(notifications)

      if (notifError) {
        console.error('Failed to create notifications:', notifError)
        // Don't fail the workflow creation, just log the error
      } else {
        console.log(`✅ Created ${notifications.length} notifications`)
      }
    }

    await triggerEmailDelivery(supabase)

    const firstSigner = signers.find(s => s.signingOrder === 1)
    const firstSignerToken = firstSigner ? accessTokens[firstSigner.email]?.token : null
    const signUrl = firstSignerToken ? `${appUrl}/sign/${firstSignerToken}` : null
    
    let debugInfo = {}
    if (Deno.env.get('ENV') === 'local') {
        debugInfo = {
            accessTokens: Object.keys(accessTokens).reduce((acc, email) => {
                const { token, tokenHash } = accessTokens[email]
                acc[email] = {
                    token,
                    tokenHash,
                    url: `${appUrl}/sign/${token}`
                }
                return acc
            }, {} as Record<string, { token: string, tokenHash: string, url: string }>)
        }
    }

    const notificationMessage = deliveryMode === 'email'
      ? requireSequential
        ? `Workflow started. ${signers.length} signer(s) added. First signer notified by email.`
        : `Workflow started. ${signers.length} signer(s) added. All signers notified by email.`
      : `Workflow started. ${signers.length} signer(s) added. Share the link manually (no email sent).`

    return jsonResponse({
      success: true,
      workflowId: workflow.id,
      versionId: version.id,
      status: workflow.status,
      deliveryMode,
      signersCount: signers.length,
      firstSignerUrl: signUrl,
      message: notificationMessage,
      _debug: debugInfo
    })

  } catch (error: any) {
    console.error('Error in start-signature-workflow:', error)
    return jsonResponse({ error: error?.message, stack: error?.stack }, 500)
  }
}))
